<?php
/**
 * DANORA - child theme for Luxrio.
 *
 * @package Danora
 */

/**
 * Enqueue light-palette overrides and child styles after Luxrio's main CSS.
 * danora-light.css is generated by tools/build_light_overrides.py.
 */
function danora_enqueue_styles() {
	$version = wp_get_theme()->get( 'Version' );

	wp_enqueue_style(
		'danora-fonts',
		'https://fonts.googleapis.com/css2?family=Cinzel:wght@500;600&family=Cormorant+Garamond:ital,wght@0,400;0,500;0,600;1,400&family=Montserrat:wght@300;400;500;600&family=Pinyon+Script&display=swap',
		array(),
		null
	);
	// Luxrio enqueues get_stylesheet_uri() as 'luxrio-style', which is this
	// file loaded *before* its main stylesheet; re-add it after instead.
	wp_dequeue_style( 'luxrio-style' );
	wp_enqueue_style( 'danora-light', get_stylesheet_directory_uri() . '/assets/css/danora-light.css', array( 'luxrio-main-style' ), $version );
	wp_enqueue_style( 'danora-style', get_stylesheet_directory_uri() . '/style.css', array( 'danora-light' ), $version );
}
add_action( 'wp_enqueue_scripts', 'danora_enqueue_styles', 100000 );

/**
 * Preconnect to Google Fonts.
 */
function danora_resource_hints( $urls, $relation_type ) {
	if ( 'preconnect' === $relation_type ) {
		$urls[] = array( 'href' => 'https://fonts.gstatic.com', 'crossorigin' );
	}
	return $urls;
}
add_filter( 'wp_resource_hints', 'danora_resource_hints', 10, 2 );

/**
 * Brand colours for the block editor palette.
 */
function danora_setup() {
	add_theme_support(
		'editor-color-palette',
		array(
			array( 'name' => 'Čierna', 'slug' => 'danora-ink', 'color' => '#1c1712' ),
			array( 'name' => 'Krémová', 'slug' => 'danora-cream', 'color' => '#f7f1e6' ),
			array( 'name' => 'Béžová', 'slug' => 'danora-beige', 'color' => '#efe4d2' ),
			array( 'name' => 'Champagne', 'slug' => 'danora-champagne', 'color' => '#e3cfae' ),
			array( 'name' => 'Zlatá', 'slug' => 'danora-gold', 'color' => '#b08d57' ),
			array( 'name' => 'Slonovina', 'slug' => 'danora-ivory', 'color' => '#fffcf6' ),
		)
	);
}
add_action( 'after_setup_theme', 'danora_setup', 20 );

/**
 * Show the transparent DANORA logo on the login screen.
 */
function danora_login_logo() {
	$logo = get_stylesheet_directory_uri() . '/assets/img/danora-logo-full.webp';
	echo '<style>
		body.login { background: #f7f1e6; }
		#login h1 a { background-image: url(' . esc_url( $logo ) . '); background-size: contain; width: 220px; height: 224px; }
		.login #backtoblog a, .login #nav a { color: #6e6358; }
		.wp-core-ui .button-primary { background: #1c1712; border-color: #1c1712; }
	</style>';
}
add_action( 'login_enqueue_scripts', 'danora_login_logo' );
