#!/usr/bin/env python3
"""Generate danora-child/assets/css/danora-light.css from Luxrio's style.css.

Luxrio is a dark theme: --white-color is used for text on dark surfaces and
dark hex values for backgrounds. Danora remaps --white-color to ink (see
style.css), so this script finds every rule that paints a *surface* with the
old light/dark values and re-emits it with Danora's cream palette.

Usage: python3 tools/build_light_overrides.py path/to/luxrio/assets/css/style.css
"""
import re
import sys

DARK_HEX = re.compile(r"#(000|000000|0[0-9a-f]{5}|1[0-9a-f]{5}|2[0-8][0-9a-f]{4})\b|(?<![-\w])black\b|var\(--black-(?:color|bg)\)", re.I)
WHITE_VAR = "var(--white-color)"
WHITE_HEX = re.compile(r"#(fff|ffffff)\b|(?<![-\w])white\b", re.I)


def parse(css):
    """Yield (at_rule_stack, selector, body) for every plain rule."""
    css = re.sub(r"/\*.*?\*/", "", css, flags=re.S)
    i, stack, out = 0, [], []
    buf = ""
    while i < len(css):
        c = css[i]
        if c == "{":
            head = buf.strip()
            buf = ""
            if head.startswith("@"):
                stack.append(head)
            else:
                j = css.index("}", i)
                out.append((tuple(stack), head, css[i + 1:j]))
                i = j
        elif c == "}":
            if stack:
                stack.pop()
            buf = ""
        else:
            buf += c
        i += 1
    return out


def fix_decl(prop, val):
    p = prop.strip().lower()
    v = val.strip()
    is_bg = p in ("background", "background-color")
    if is_bg and WHITE_VAR in v:
        return p, "var(--dn-surface)"
    if is_bg and DARK_HEX.search(v) and "gradient" not in v and "url(" not in v:
        return p, "var(--dn-cream-deep)"
    if p == "color" and WHITE_HEX.search(v):
        return p, "var(--dn-ink)"
    if p.startswith("border") and WHITE_VAR in v:
        return p, v.replace(WHITE_VAR, "var(--dn-line)")
    if p.startswith("border") and DARK_HEX.search(v):
        return p, DARK_HEX.sub("var(--dn-line)", v)
    if "rgba(255, 255, 255" in v and p in ("color", "border-color", "background-color", "border", "border-top", "border-bottom"):
        return p, v.replace("rgba(255, 255, 255", "rgba(28, 23, 18")
    return None


def main(src):
    rules = parse(open(src, encoding="utf-8").read())
    groups = {}
    for stack, sel, body in rules:
        if sel.startswith(":root") or "@keyframes" in " ".join(stack) or not sel:
            continue
        fixed = []
        for decl in body.split(";"):
            if ":" not in decl:
                continue
            prop, val = decl.split(":", 1)
            r = fix_decl(prop, val)
            if r:
                fixed.append(f"{r[0]}: {r[1]}")
        if fixed:
            groups.setdefault(stack, []).append((sel, fixed))
    lines = ["/* AUTO-GENERATED by tools/build_light_overrides.py - do not edit by hand. */"]
    for stack, items in groups.items():
        ind = "  " * len(stack)
        for s in stack:
            lines.append(s + " {")
        for sel, fixed in items:
            sel = re.sub(r"\s+", " ", sel)
            lines.append(f"{ind}{sel} {{ " + "; ".join(fixed) + "; }")
        for _ in stack:
            lines.append("}")
    print("\n".join(lines))
    print(f"/* {sum(len(v) for v in groups.values())} rules */", file=sys.stderr)


if __name__ == "__main__":
    main(sys.argv[1])
